### PR TITLE
Increased base min-font size from 10px to 13px

### PR DESCRIPTION
**Pull request by abass**
You have to be careful when dealing with a minimum font size on mobile. Just because the screen shrinks doesn't mean you can go overboard with shrinking the text. To be safe, you really don't want to ever go below 13px on mobile (maybe sometimes 12px will fly, but 10px is just TOO small and brings up tons of usability problems).

Simple update that just replaces the min-font size to 13px from 10px.

Loving the new typographic Cory, keep it up!

### CODE REVIEW

**Comment by corysimmons** [comment]
@flip4bytes Thanks for the PR and the kind words Alex. Would you mind bumping up the `$max-font` to `18` or `20` as well so users can see all the responsive scaling goodness that happens between breakpoints?

**Comment by corysimmons** [comment]
`13` - `16` just doesn't seem like a big enough of a difference to me. =)

**Comment by flip4bytes** [comment]
Yeah, absolutely. If you want to check out how big of a difference it is, on my personal site I use 20px on desktop and a min size of 13px - [Why You Should Run Usability Testing On Everything](https://abass.co/blog/why-you-should-run-usability-testing-everything)

I know some people love having really small font sizes on desktop and others like to have REALLY big font sizes to make up for the screen real estate but 20px is a good medium for usability and functionality imho.

**Comment by corysimmons** [comment]
`20px` sounds good to me. Amend your commit then `git push -f`.

Your website looks great btw. Glad some of my tools are being used on beautiful sites. =)

**Comment by flip4bytes** [comment]
Appreciate the kind words! I'll definitely be using typographic on this project I'm starting now and I'm still trying to make up my mind because I really love flexgrid and I only need to support current browser and 1 version back.. But I might go with [LostGrid](https://github.com/corysimmons/lost). Still not sure, stuck between a rock and a hard place right now! I love flexbox so much :'(

**Comment by corysimmons** [comment]
I highly suggest you use Lost Grid **until I get a chance to do a thorough revisiting of Flexgrid**. I don't feel like I did it justice the first time around.

I love flex too and think it should be used for a ton of layout choices but Lost provides an absolutely rock solid flexible grid system that works with masonry and without the bloat of Jeet.

Thanks for the PRs!

**Comment by flip4bytes** [comment]
Alright cory, FINE. You sold me, I have faith in you. (Though I do really look forward to seeing your flexgrid redesign). I think the only reason it didn't get as much publicity as Lost Grid is getting now is because it's poor backwards compatibility and for some people, that's SO important. As flexbox and calc get more rock solid browser support, I think Flexgrid could really kickass.

Either way, really happy to see you so active again! You went MIA for some time, I got a bit worried.. You're my main grid system & stylus buddy! Haha hope all is well, keep it up man!

**Comment by corysimmons** [comment]
I think Flexgrid didn't get as popular as my other grids because 1) I didn't market it at all 2) it wasn't super great, it was literally a first pass on a technology I was still getting familiar with 3) http://flexboxgrid.com exists already and does a fine job of being *the* flexbox grid out there right now.

When I revisit it, Flexgrid will blow away Flexboxgrid though. Hell, just getting rid of those ugly Bootstrap classes will make it the better grid system.

> Either way, really happy to see you so active again! You went MIA for some time, I got a bit worried.. You're my main grid system & stylus buddy! Haha hope all is well, keep it up man!

Yeah I got super depressed for a few months and didn't really do anything. After a life of struggling with on/off depression I finally got on meds and they perked me right up. Hopefully I'll be this productive for years to come. In the meantime, enjoy it while it lasts. =)

**Comment by corysimmons** [comment]
:+1:

**Comment by flip4bytes** [comment]
Gotcha, but yeah, **exactly**! Using bootstrap classes like that after having gotten so used to Jeet and your newer systems makes me not want to touch [flexboxgrid](http://flexboxgrid.com/) it with a 10 foot pole! For some people though, that's just all they know. IMHO all those bootstrap grid systems now probably appeal to back-end developers who are just throwing together a front-end just because they need something there. I can't imagine being a full-on front-end dev now-a-days and not using some type of flexible grid system without predefined classes. It forces the design to be built within the restrictions of the framework rather than the framework to be built around the design.

Anyway, glad everything is going well now! We need you in this community man, don't go disappearing again, my business depends on you! (p.s.  [LaunchBox](http://launchboxhq.com/) website looks really great man!)

**Comment by corysimmons** [comment]
> It forces the design to be built within the restrictions of the framework rather than the framework to be built around the design.

Couldn't agree more.

Thanks for your kind words.

Before you go, did you see https://github.com/corysimmons/typographic/pull/26 ?

**Comment by flip4bytes** [comment]
Yep! My bad, just fixed it. :+1:

**Comment by corysimmons** [comment]
Thanks! Got em merged!

**Pull request merged**
