### PR TITLE
Added meta viewport & Increased base min-font size from 10px to 13px

### PR DESCRIPTION
**Pull request by abass**
Just threw in a metaviewport so this renders properly on mobile devices and increased the minimum font size to mirror the change in typographic.

### CODE REVIEW

**Comment by corysimmons** [comment]
Again, could you bump `$max-font` up to `18` or `20` please? Thanks for the lovely PRs. =)

**Comment by flip4bytes** [comment]
You got it :+1:

**Comment by flip4bytes** [comment]
Shoot, my bad! Doing that right now!

**Comment by corysimmons** [comment]
Thank you! :+1:

**Pull request merged**
