### PR TITLE
Change "header" to "heading"

### PR DESCRIPTION
**Pull request by janwirth**

### CODE REVIEW

**Comment by corysimmons** [comment]
Is this just a preference or is there something I'm missing?

Also, you'd need to version bump package.json according to [semver](http://semver.org/) and completely remove the `version` field in bower.json.

**Comment by FranzSkuffka** [comment]
TL;DR;

header ->    `<header>`
heading ->   `<h1>`, `<h2>`, `<h3>`, ...

I'm not a native english speaker and I was hitting the dict before filing this request.
AFAIK:
`h1` etc are headings or headlines of text bodies. Multiple headings per page are possible.
a header is what I would use the HTML5 `<header>` element for. A singular bar at the top of the pape.

So like pretty much everything it's debatable but I am pretty convinced 'heading' is the more correct term in the frontend-o-sphere for what the code is describing.

**Comment by corysimmons** [comment]
Yup, Google'd for about 3 minutes before I realized what a tragic mistake I've made.

I'll merge this if you add the package.json and bower.json version modifications I asked for. :+1:

**Comment by FranzSkuffka** [comment]
Did I tell you I suck at reading? On it.

**Comment by corysimmons** [comment]
That reminds me. I haven't read a book in years... Now I'm sad... and stupid...

**Comment by FranzSkuffka** [comment]
semver isn't about odd or even version numbers, right? This was some other thing. So just a minor bump.

**Comment by FranzSkuffka** [comment]
I'm just praying I did not break something. grep returns no occurences for `header` though.

**Comment by corysimmons** [comment]
No it's a major version bump because it breaks the API.

If I have a SCSS file that looks like this:

```scss
h3 {
  @include t-header();
}
```

And I update my Bower and recompile my site, it's not going to work anymore.

**Comment by FranzSkuffka** [comment]
You're right. Like this?

**Comment by corysimmons** [comment]
image

^ what's it say :D

**Comment by FranzSkuffka** [comment]
It says that I am a bad person.

**Comment by corysimmons** [comment]
:+1: :100:

**Comment by corysimmons** [comment]
Thanks sir!

**Comment by FranzSkuffka** [comment]
This was way to granular.
Glad if I can give something back :facepunch:

**Pull request merged**
